languageCode = "en"
languageName = "English"
weight = 1
title = "*Who* are you drinking?"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/beer_mug.png"
  # secondaryLogo = "PATH"
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "tornADA"
  image = "img/beer_mug.png"
  # links = [{ github = "https://github.com/epfl-ada/ada-2023-project-tornada" },]

  